export const table_data = [
    {
        name: "3.3.1-14Ar-4Эл",
        tags: ['hitproof', 'soundproof', 'multi'],
        cams: 1,
        depth: 24,
        Ro: 0.91,
        Rw: 35,
        Lt: 71,
        Lr: 13,
        Ra: 95,
        Det: 34,
        Er: 40,
        Ea: 26,
        Sf: 38,
        Sc: 0.44,
        S: 1.87,
        weight: 37,
        secure: "P2A",
    },
    {
        name: "4-16Ar-4Эл",
        tags: ['multi'],
        cams: 1,
        depth: 24,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-14Ar-6(FHcl)",
        tags: ['soundproof', 'solarproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-16Ar-4(FHcl)",
        tags: ['solarproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "6TopN-10Ar-4.4.1",
        tags: ['hitproof', 'soundproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-12Ar-4.4.1",
        tags: ['hitproof', 'soundproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-14Ar-3.3.1",
        tags: ['hitproof', 'soundproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-16Ar-4Сбр",
        tags: ['solarproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-16-4",
        tags: ['simple'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-12-4.4.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "6-10-4.4.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-14-3.3.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-14-6",
        tags: ['soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-16-4",
        tags: ['simple'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-6-4-6-4",
        tags: ['simple'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "6-14Ar-4Эл",
        tags: ['multi', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-20Ar-4Эл",
        tags: ['multi',],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-20Ar-4(FHcl)",
        tags: ['solarproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-20Ar-4Сбр",
        tags: ['solarproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-20-4",
        tags: ['simple'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-20-4",
        tags: ['simple'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "3.3.1-10-4-12Ar-4Эл",
        tags: ['hitproof', 'soundproof', 'multi'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "6-10-4-12Ar-4Эл",
        tags: ['multi', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-12-4-12Ar-4Эл",
        tags: ['multi'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-12Ar-4-12-4(FHcl)",
        tags: ['solarproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "6TopN-9Ar-4-9-4.4.1",
        tags: ['hitproof', 'energy', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-10Ar-4-10-4.4.1",
        tags: ['hitproof', 'energy', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-10ARr-4-12-3.3.1",
        tags: ['hitproof', 'energy', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-12Ar-4TopN-12Ar-4",
        tags: ['energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-12-4-12Ar-4Сбр",
        tags: ['solarproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "6-9-4-9-4.4.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-10-4-10-4.4.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-10-4-12-3.3.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4.4.1-24-4.4.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-12-4-16Ar-4Эл",
        tags: ['multi'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-14-4-14Ar-4Эл",
        tags: ['multi'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-14-4-14-4Эл",
        tags: ['multi'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-12Ar-4-12-4.4.1",
        tags: ['hitproof', 'soundproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-12Ar-4-14-3.3.1",
        tags: ['hitproof', 'soundproof', 'energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-14Ar-4TopN-14Ar-4",
        tags: ['energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-12Ar-4-14-6",
        tags: ['energy', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4TopN-14Ar-4-14-4",
        tags: ['energy'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-12-4-12-4.4.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-12-4-12-3.3.1",
        tags: ['hitproof', 'soundproof'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
    {
        name: "4-14-4-14-4",
        tags: ['simple'],
        cams: 0,
        depth: 0,
        Ro: 0,
        Rw: 0,
        Lt: 0,
        Lr: 0,
        Ra: 0,
        Det: 0,
        Er: 0,
        Ea: 0,
        Sf: 0,
        Sc: 0,
        S: 0,
        weight: 0,
        secure: "",
    },
]
